version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pip install pytest
      - (cd tests; pytest test_endpoints.py)
      - (cd tests; pytest unit_tests.py)