version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pytest tests/unit_tests.py
      - pytest tests/test_endpoints.py
