version: "3"
services:
  flask_api:
    build: .
    ports:
      - "5000:5000"
  postgres:
    image: "postgres:13.2"
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGERS_DB=Flask_REST_API
